### ISSUE TITLE
FLUSH _len problem

### ISSUE THREAD

**Issue by scottypitcher** [jd-boyd/MAKE_FIFO#1]
Calling FLUSH() while the FIFO contains data, doesn't clear the _len field. After this, the _len field retains it's old value, but _next_in and _next_out are the same, and FIFO is permanently reduced in size by _len elements.

FLUSH should be changed to:
#define FLUSH(prefix) { \
    prefix ##_len = prefix ##_next_in  = prefix ##_next_out = 0; \
}

**Comment by jd-boyd** [comment]
Thank you for the suggestion. Please consider making a pull request.

**Comment by jd-boyd** [comment]
Fixed by #2
